// <auto-generated />
using Knowleture_Data.Data;
using Knowleture_Data.Enumerations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Knowleture_Data.Migrations
{
    [DbContext(typeof(KnowletureContext))]
    [Migration("20171107041105_newPasswordProperties")]
    partial class newPasswordProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Knowleture_Data.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowUpload");

                    b.Property<int>("AverageScore");

                    b.Property<int>("CourseId");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("FileType");

                    b.Property<int>("MaxScore");

                    b.Property<string>("Objective");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Title");

                    b.Property<string>("UploadDirectory");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Course", b =>
                {
                    b.Property<int>("CourseId");

                    b.Property<string>("Code");

                    b.Property<int>("Credit");

                    b.Property<int>("DepartmentId");

                    b.Property<string>("Subject");

                    b.Property<string>("Term");

                    b.Property<string>("Title");

                    b.Property<int>("Year");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Knowleture_Data.Models.CourseAssignment", b =>
                {
                    b.Property<int>("CourseId");

                    b.Property<int>("UserId");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseAssignment");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CourseId");

                    b.Property<int?>("Grade");

                    b.Property<string>("Term");

                    b.Property<int>("UserId");

                    b.Property<int>("Year");

                    b.HasKey("EnrollId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Office", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("Days");

                    b.Property<string>("Hours");

                    b.Property<string>("Location");

                    b.Property<string>("OfficeNumber");

                    b.HasKey("UserId");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("RoleName");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Knowleture_Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FacebookLink");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("LastName");

                    b.Property<string>("LinkedInLink");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Summary");

                    b.Property<string>("TwitterLink");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Knowleture_Data.Models.UserRoles", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Instructor", b =>
                {
                    b.HasBaseType("Knowleture_Data.Models.User");

                    b.Property<int?>("CourseId");

                    b.Property<string>("Department");

                    b.HasIndex("CourseId");

                    b.ToTable("Instructor");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Student", b =>
                {
                    b.HasBaseType("Knowleture_Data.Models.User");

                    b.Property<string>("Major");

                    b.ToTable("Student");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Knowleture_Data.Models.Assignment", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.Course", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.CourseAssignment", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Course", "Course")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowleture_Data.Models.Instructor", "Instructor")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.Department", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.Enrollment", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowleture_Data.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.Office", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Instructor", "Instructor")
                        .WithOne("Office")
                        .HasForeignKey("Knowleture_Data.Models.Office", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.UserRoles", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Knowleture_Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Knowleture_Data.Models.Instructor", b =>
                {
                    b.HasOne("Knowleture_Data.Models.Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
